## Update an identity profile

PUT http://localhost:3000/identity/profile/did:entity-storage:0x33e61d1f90a2afee012064cf2cb35783dfecee4621c247734b98e4fa47fc1d4b
x-api-key: fu2NApKBVBJyEVotdazUQZAO34/gEytqV9u4rGElRKk=
authorization: Bearer eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6aW90YTp0c3Q6MHhhOThiZjYzMzgxYjRlMTAxZGQ4MjVhMmU2YzBiZWI2OTAyYThhNjNlMDc5YTgwNzA4ZDg5ZThjMTY5ZWNhMGJjIiwiZXhwIjoxNzIyMDg4MDkyfQ._EmQO9tDtG0Bo0bg7TDf5bgVnYthSRtIflIR2ECasqSvKauq9LHNC6828Nyh9zQ95F5XSVQAMN8X2KpMHpBtDg
content-type: application/json

{
	"properties": [
    {
      "key": "role",
      "type": "https://schema.org/Text",
      "value": "User",
      "isPublic": false
    },
    {
      "key": "name",
      "type": "https://schema.org/Text",
      "value": "John Smith",
      "isPublic": true
    }
  ]
}
