## Update an identity profile

PUT http://localhost:3000/identity/profile
cookie: access_token=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZW50aXR5LXN0b3JhZ2U6MHgyNzViYTQ5NWI2ZmM2MzU5NDhmMjU2OGY1MmFmYjc5NzIwMDc4N2U5ZjcxZTBiNDFlZGI2MmNlN2UzYzg0NjRjIiwiZXhwIjoxNzI3MTczMTk2fQ.NqMRqJpjFb8z930coyCGPnFJVNlnDCExk8c07LzXuhSEvM3KaX5ViMJ2VXucDwVocKc2j7hGFHpjsRn6q8TUDA
content-type: application/json

{
	"properties": [
    {
      "key": "role",
      "type": "https://schema.org/Text",
      "value": "User",
      "isPublic": false
    },
    {
      "key": "name",
      "type": "https://schema.org/Text",
      "value": "John Smith",
      "isPublic": true
    }
  ]
}
