### Deletes a blob

DELETE http://localhost:3000/blob-storage/blob:file:7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069
cookie: access_token=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZW50aXR5LXN0b3JhZ2U6MHgyNzViYTQ5NWI2ZmM2MzU5NDhmMjU2OGY1MmFmYjc5NzIwMDc4N2U5ZjcxZTBiNDFlZGI2MmNlN2UzYzg0NjRjIiwiZXhwIjoxNzI3MTczMTk2fQ.NqMRqJpjFb8z930coyCGPnFJVNlnDCExk8c07LzXuhSEvM3KaX5ViMJ2VXucDwVocKc2j7hGFHpjsRn6q8TUDA
content-type: application/json
