### Gets a blob content

GET http://localhost:3000/blob-storage/blob:file:5c15f3a70dffb7bf79576858c75c173f5240f676ebe21161130466bf1db7c1af/content
cookie: access_token=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZW50aXR5LXN0b3JhZ2U6MHgyNzViYTQ5NWI2ZmM2MzU5NDhmMjU2OGY1MmFmYjc5NzIwMDc4N2U5ZjcxZTBiNDFlZGI2MmNlN2UzYzg0NjRjIiwiZXhwIjoxNzI3MTczMTk2fQ.NqMRqJpjFb8z930coyCGPnFJVNlnDCExk8c07LzXuhSEvM3KaX5ViMJ2VXucDwVocKc2j7hGFHpjsRn6q8TUDA
content-type: application/json
