### Get an auditable item graph vertex verifying no signatures

GET http://localhost:3000/aig/aig:8d6cc7d02c1cb59c12256b6ba9eca1a247c0855928fb5d7bd6e0dcc90b4198b3?includeChangesets=true
cookie: access_token=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6aW90YTp0c3Q6MHgwNzI1Zjk1N2QwMGQ1OTdkMTI5NTE2ZmYxYmRlOTc4Nzg5ZWNhZDg3MGYxYThkNTc1NzMxZGExZmMyMGU1ZDNkIiwiZXhwIjoxNzI1MzYzNDA3fQ.9J7uKhRfvm_JGnN6bGFJqZA9MY4zMzr-sWNIejCQjU0R5Gs4s2D849SOc9UXF0R3ur3kPps3GqB9VcySYQbIAA


### Get an auditable item graph vertex verifying current signature

GET http://localhost:3000/aig/aig:8d6cc7d02c1cb59c12256b6ba9eca1a247c0855928fb5d7bd6e0dcc90b4198b3?includeChangesets=true&verifySignatureDepth=current
cookie: access_token=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6aW90YTp0c3Q6MHgwNzI1Zjk1N2QwMGQ1OTdkMTI5NTE2ZmYxYmRlOTc4Nzg5ZWNhZDg3MGYxYThkNTc1NzMxZGExZmMyMGU1ZDNkIiwiZXhwIjoxNzI1MzYzNDA3fQ.9J7uKhRfvm_JGnN6bGFJqZA9MY4zMzr-sWNIejCQjU0R5Gs4s2D849SOc9UXF0R3ur3kPps3GqB9VcySYQbIAA

### Get an auditable item graph vertex verifying all signatures

GET http://localhost:3000/aig/aig:8d6cc7d02c1cb59c12256b6ba9eca1a247c0855928fb5d7bd6e0dcc90b4198b3?includeChangesets=true&verifySignatureDepth=all
cookie: access_token=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6aW90YTp0c3Q6MHgwNzI1Zjk1N2QwMGQ1OTdkMTI5NTE2ZmYxYmRlOTc4Nzg5ZWNhZDg3MGYxYThkNTc1NzMxZGExZmMyMGU1ZDNkIiwiZXhwIjoxNzI1MzYzNDA3fQ.9J7uKhRfvm_JGnN6bGFJqZA9MY4zMzr-sWNIejCQjU0R5Gs4s2D849SOc9UXF0R3ur3kPps3GqB9VcySYQbIAA
