### Creates an attestation

POST http://localhost:3000/attestation
cookie: access_token=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZW50aXR5LXN0b3JhZ2U6MHg2YjE1OGM0YTRlMjI4YmY4Y2IxOGNlMjUzMmMyZjA0MGQ2ZDE1NGYzOTE5NzMzZTBlOTkyYmFlM2NmMmEzNWY3IiwiZXhwIjoxNzIzNzE1Nzc0fQ.ztjOHs9BNugO97oxA1rIMBSy2JP3pYqOjeGZsvv9NqhzaXhK5DLr4rnlf3bpoyIvFlJfxKNnwGTi7pUcmQ6oDw
content-type: application/json

{
	"address": "tst1qzcs7xqax2rajn6kn5y52w2x9x7q3qvfphf0nte7yjpswufvgasrstt4eny",
  	"verificationMethodId": "did:iota:tst:0xeb669c32b08e73e00b2f3afc0bb94913329a7f70d3ca78a7c29f42178aa3bc63#attestation",
  	"data": {
    	"docName": "bill-of-lading",
    	"mimeType": "application/pdf",
    	"fingerprint": "0xf0b95a98b3dbc5ce1c9ce59d70af95a97599f100a7296ecdd1eb108bebfa047f"
  	}
}

