### Transfers an attestation

PUT http://localhost:3000/attestation/attestation:iota:bmZ0OmlvdGE6dHN0OjB4YzQ4ODNhMzc1YzZjN2E2Mzk0YjgwZmVhMjRhN2FkZGIyZGU3MWZkZjVlNjQyYjg1MGI1YmRkNjgxNjJlZDk4Nw==/transfer
cookie: access_token=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZW50aXR5LXN0b3JhZ2U6MHg2YjE1OGM0YTRlMjI4YmY4Y2IxOGNlMjUzMmMyZjA0MGQ2ZDE1NGYzOTE5NzMzZTBlOTkyYmFlM2NmMmEzNWY3IiwiZXhwIjoxNzIzNzE1Nzc0fQ.ztjOHs9BNugO97oxA1rIMBSy2JP3pYqOjeGZsvv9NqhzaXhK5DLr4rnlf3bpoyIvFlJfxKNnwGTi7pUcmQ6oDw
content-type: application/json

{
	"holderAddress": "tst1qrdd3m2t3hel3pjksr4ld8kfj48yxklpru3emv7wejhdp9fd24dhq4h9pv8",
	"holderIdentity": "did:iota:tst:0xeb669c32b08e73e00b2f3afc0bb94913329a7f70d3ca78a7c29f42178aa3bc63"
}

