### Lists log entries

GET http://localhost:3000/logging
x-api-key: fu2NApKBVBJyEVotdazUQZAO34/gEytqV9u4rGElRKk=
authorization: Bearer eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6aW90YTp0c3Q6MHhhOThiZjYzMzgxYjRlMTAxZGQ4MjVhMmU2YzBiZWI2OTAyYThhNjNlMDc5YTgwNzA4ZDg5ZThjMTY5ZWNhMGJjIiwiZXhwIjoxNzIyNDExODY1fQ._Ph9eCZQVpX5HuR72hiGOI5zIlJ0wQsijadOjpQRNsABOv8-ZqGTWQxmtDF68dFGtY9PQ7IbjHrbBg_KBqclAw
