### Creates a blob

POST http://localhost:3000/blob-storage
x-api-key: RIBJU/z/ADk2+OZTvgmYtMLoNhwVoDAXyFVWzbBEfQ8=
authorization: Bearer eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6aW90YTp0c3Q6MHhlMzA4OGJhOWFhOGMyOGUxZDEzOTcwOGExNGU4YzBmZGZmMTFlZTgyMjNiYWFjNGFhNWJjZjMzMjFlNGJmYzZhIiwiZXhwIjoxNzIxOTgzMDgyfQ.VphjheFmM_q5WNzQI8gVi-zkis_tPEvjbgz_82oTny6DHvdoq7nr4OD0Z0K6KhPUgHEu4u5hCvWGeBGKNq-TAQ
content-type: application/json

{
	"blob": "SGVsbG8gV29ybGQh"
}
