### Deletes a blob

DELETE http://localhost:3000/blob-storage/blob:file:7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069
x-api-key: fu2NApKBVBJyEVotdazUQZAO34/gEytqV9u4rGElRKk=
authorization: Bearer eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6aW90YTp0c3Q6MHhhOThiZjYzMzgxYjRlMTAxZGQ4MjVhMmU2YzBiZWI2OTAyYThhNjNlMDc5YTgwNzA4ZDg5ZThjMTY5ZWNhMGJjIiwiZXhwIjoxNzIyMDg4MDkyfQ._EmQO9tDtG0Bo0bg7TDf5bgVnYthSRtIflIR2ECasqSvKauq9LHNC6828Nyh9zQ95F5XSVQAMN8X2KpMHpBtDg
content-type: application/json
