### Gets a blob

GET http://localhost:3000/blob-storage/blob:file:7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069
x-api-key: RIBJU/z/ADk2+OZTvgmYtMLoNhwVoDAXyFVWzbBEfQ8=
authorization: Bearer eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6aW90YTp0c3Q6MHhlMzA4OGJhOWFhOGMyOGUxZDEzOTcwOGExNGU4YzBmZGZmMTFlZTgyMjNiYWFjNGFhNWJjZjMzMjFlNGJmYzZhIiwiZXhwIjoxNzIxOTgzMDgyfQ.VphjheFmM_q5WNzQI8gVi-zkis_tPEvjbgz_82oTny6DHvdoq7nr4OD0Z0K6KhPUgHEu4u5hCvWGeBGKNq-TAQ
content-type: application/json
