### Fails with no API Key
POST http://localhost:3000/identity
content-type: application/json

{
	"controller": "tst1qrlrpvm5yu2ue0hhzk332uhhh4e7gh6ka26c8xq6sfvcl2d4pfuag95qy9n"
}


### Creates an identity
POST http://localhost:3000/identity
x-api-key: fu2NApKBVBJyEVotdazUQZAO34/gEytqV9u4rGElRKk=
authorization: Bearer eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6aW90YTp0c3Q6MHhhOThiZjYzMzgxYjRlMTAxZGQ4MjVhMmU2YzBiZWI2OTAyYThhNjNlMDc5YTgwNzA4ZDg5ZThjMTY5ZWNhMGJjIiwiZXhwIjoxNzIyNDExODY1fQ._Ph9eCZQVpX5HuR72hiGOI5zIlJ0wQsijadOjpQRNsABOv8-ZqGTWQxmtDF68dFGtY9PQ7IbjHrbBg_KBqclAw
content-type: application/json

{
	"controller": "tst1qrlrpvm5yu2ue0hhzk332uhhh4e7gh6ka26c8xq6sfvcl2d4pfuag95qy9n"
}
