### Resolves an identity
GET http://localhost:3000/identity/did:entity-storage:0x0fe5c3da48bb0377e0514f0caf43a55a1e480465a1f937188409ad9549130174
cookie: access_token=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6aW90YTp0c3Q6MHgwNzI1Zjk1N2QwMGQ1OTdkMTI5NTE2ZmYxYmRlOTc4Nzg5ZWNhZDg3MGYxYThkNTc1NzMxZGExZmMyMGU1ZDNkIiwiZXhwIjoxNzI1MzYzNDA3fQ.9J7uKhRfvm_JGnN6bGFJqZA9MY4zMzr-sWNIejCQjU0R5Gs4s2D849SOc9UXF0R3ur3kPps3GqB9VcySYQbIAA
