### Gets a blob

GET http://localhost:3000/blob-storage/blob:file:7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069
cookie: access_token=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6aW90YTp0c3Q6MHhlYjY2OWMzMmIwOGU3M2UwMGIyZjNhZmMwYmI5NDkxMzMyOWE3ZjcwZDNjYTc4YTdjMjlmNDIxNzhhYTNiYzYzIiwiZXhwIjoxNzIyOTM3MDc3fQ.HdPTasafY307PzP6gUrczSwzuF0GPZ2d-ecAtJh6zBrQFuq4hB2T163s-tGmcPahwrFA9lasBT13vL5GyoBICQ
content-type: application/json
