### Fails with no API Key
POST http://localhost:3000/identity
content-type: application/json

{
	"controller": "tst1qrvkjfl2eex7hz4ylqxulq2aeyht8jadwmlcjzjfp2g0vzjd2aue54fx9w5"
}


### Creates an identity
POST http://localhost:3000/identity
x-api-key: RIBJU/z/ADk2+OZTvgmYtMLoNhwVoDAXyFVWzbBEfQ8=
authorization: Bearer eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6aW90YTp0c3Q6MHhlMzA4OGJhOWFhOGMyOGUxZDEzOTcwOGExNGU4YzBmZGZmMTFlZTgyMjNiYWFjNGFhNWJjZjMzMjFlNGJmYzZhIiwiZXhwIjoxNzIxODkyMzI2fQ.WDQV-ZVX_yw-22mP17XzZ7reetcznyTKzt9SnltLheb2qvctgfknZPIWrgfX73yHjOU2TWiQJ71uiUYwmIPLCQ
content-type: application/json

{
	"controller": "tst1qrvkjfl2eex7hz4ylqxulq2aeyht8jadwmlcjzjfp2g0vzjd2aue54fx9w5"
}
