### Fails with no API Key
POST http://localhost:3000/identity
content-type: application/json

{
	"controller": "tst1qrlrpvm5yu2ue0hhzk332uhhh4e7gh6ka26c8xq6sfvcl2d4pfuag95qy9n"
}


### Creates an identity
POST http://localhost:3000/identity
x-api-key: fu2NApKBVBJyEVotdazUQZAO34/gEytqV9u4rGElRKk=
authorization: Bearer eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6aW90YTp0c3Q6MHhhOThiZjYzMzgxYjRlMTAxZGQ4MjVhMmU2YzBiZWI2OTAyYThhNjNlMDc5YTgwNzA4ZDg5ZThjMTY5ZWNhMGJjIiwiZXhwIjoxNzIyMDg4MDkyfQ._EmQO9tDtG0Bo0bg7TDf5bgVnYthSRtIflIR2ECasqSvKauq9LHNC6828Nyh9zQ95F5XSVQAMN8X2KpMHpBtDg
content-type: application/json

{
	"controller": "tst1qrlrpvm5yu2ue0hhzk332uhhh4e7gh6ka26c8xq6sfvcl2d4pfuag95qy9n"
}
