### With no API Key should auth fail with apiKeyMissing
GET http://localhost:3000/health

### With API Key should return
GET http://localhost:3000/health
x-api-key: EIkiS72T/rLTd4LvMcdHK73lIrPg/mPo8scHcxql/UQ=

