### With no API Key should auth fail with apiKeyMissing
GET http://localhost:3000/spec

### With API Key should return
GET http://localhost:3000/spec
x-api-key: RIBJU/z/ADk2+OZTvgmYtMLoNhwVoDAXyFVWzbBEfQ8=

