### With no API Key should auth fail with apiKeyMissing
GET http://localhost:3000/info


### With API Key should return
GET http://localhost:3000/info
x-api-key: fu2NApKBVBJyEVotdazUQZAO34/gEytqV9u4rGElRKk=

