### Creates an attestation

POST http://localhost:3000/attestation
x-api-key: fu2NApKBVBJyEVotdazUQZAO34/gEytqV9u4rGElRKk=
authorization: Bearer eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6aW90YTp0c3Q6MHhhOThiZjYzMzgxYjRlMTAxZGQ4MjVhMmU2YzBiZWI2OTAyYThhNjNlMDc5YTgwNzA4ZDg5ZThjMTY5ZWNhMGJjIiwiZXhwIjoxNzIyNDExODY1fQ._Ph9eCZQVpX5HuR72hiGOI5zIlJ0wQsijadOjpQRNsABOv8-ZqGTWQxmtDF68dFGtY9PQ7IbjHrbBg_KBqclAw
content-type: application/json

{
	"controllerAddress": "tst1qrlrpvm5yu2ue0hhzk332uhhh4e7gh6ka26c8xq6sfvcl2d4pfuag95qy9n",
  	"verificationMethodId": "did:iota:tst:0xa98bf63381b4e101dd825a2e6c0beb6902a8a63e079a80708d89e8c169eca0bc#attestation",
  	"data": {
    	"docName": "bill-of-lading",
    	"mimeType": "application/pdf",
    	"fingerprint": "0xf0b95a98b3dbc5ce1c9ce59d70af95a97599f100a7296ecdd1eb108bebfa047f"
  	}
}

