### Get an attestation

GET http://localhost:3000/attestation/attestation:iota:bmZ0OmlvdGE6dHN0OjB4MDQwYzY2MWJjZjkxMzQ3NDlmNjEzYzRkZTk2MjU2YzRiMTA0MTQ2Zjc3MzYyMDBlM2YyMTBkZDVjNzQ1NGE4Yg==
x-api-key: fu2NApKBVBJyEVotdazUQZAO34/gEytqV9u4rGElRKk=
authorization: Bearer eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6aW90YTp0c3Q6MHhhOThiZjYzMzgxYjRlMTAxZGQ4MjVhMmU2YzBiZWI2OTAyYThhNjNlMDc5YTgwNzA4ZDg5ZThjMTY5ZWNhMGJjIiwiZXhwIjoxNzIyNDExODY1fQ._Ph9eCZQVpX5HuR72hiGOI5zIlJ0wQsijadOjpQRNsABOv8-ZqGTWQxmtDF68dFGtY9PQ7IbjHrbBg_KBqclAw
