### Fails with no API Key
POST http://localhost:3000/authentication/login
content-type: application/json

{
	"email": "a@example.com"
}


### Login
POST http://localhost:3000/authentication/login
x-api-key: EIkiS72T/rLTd4LvMcdHK73lIrPg/mPo8scHcxql/UQ=
content-type: application/json

{
	"email": "system@system",
	"password": "wEX3#ggw=x@gQfG2"
}
