### Creates an nft

POST http://localhost:3000/nft
cookie: access_token=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZW50aXR5LXN0b3JhZ2U6MHgyNzViYTQ5NWI2ZmM2MzU5NDhmMjU2OGY1MmFmYjc5NzIwMDc4N2U5ZjcxZTBiNDFlZGI2MmNlN2UzYzg0NjRjIiwiZXhwIjoxNzI3MTczMTk2fQ.NqMRqJpjFb8z930coyCGPnFJVNlnDCExk8c07LzXuhSEvM3KaX5ViMJ2VXucDwVocKc2j7hGFHpjsRn6q8TUDA
content-type: application/json

{
	"issuer": "tst1qzcs7xqax2rajn6kn5y52w2x9x7q3qvfphf0nte7yjpswufvgasrstt4eny",
	"tag": "MY_NFT",
	"immutableMetadata": {
		"name": "My NFT",
		"description": "My first NFT",
		"image": "https://example.com/image.jpg"
	},
	"metadata": {
		"someProp": 123
	}
}
