### Transfer an nft

POST http://localhost:3000/nft/nft:entity-storage:0x677843a58afc0ebee7e63911be6dac79eac3b1f92af7d971e96df65766a730a1/transfer
cookie: access_token=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZW50aXR5LXN0b3JhZ2U6MHg2YjE1OGM0YTRlMjI4YmY4Y2IxOGNlMjUzMmMyZjA0MGQ2ZDE1NGYzOTE5NzMzZTBlOTkyYmFlM2NmMmEzNWY3IiwiZXhwIjoxNzIzNzE1Nzc0fQ.ztjOHs9BNugO97oxA1rIMBSy2JP3pYqOjeGZsvv9NqhzaXhK5DLr4rnlf3bpoyIvFlJfxKNnwGTi7pUcmQ6oDw
content-type: application/json

{
	"recipient": "did:entity-storage:0x1fe5c3da48bb0377e0514f0caf43a55a1e480465a1f937188409ad9549130174"
}
