### Get an nft

GET http://localhost:3000/nft/nft:entity-storage:0x08f02fcd71fdd01bc1f0f812ccd4af5240543212bccbb58f70e69a0d5101b5b4
x-api-key: RIBJU/z/ADk2+OZTvgmYtMLoNhwVoDAXyFVWzbBEfQ8=
authorization: Bearer eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6aW90YTp0c3Q6MHhlMzA4OGJhOWFhOGMyOGUxZDEzOTcwOGExNGU4YzBmZGZmMTFlZTgyMjNiYWFjNGFhNWJjZjMzMjFlNGJmYzZhIiwiZXhwIjoxNzIxOTgzMDgyfQ.VphjheFmM_q5WNzQI8gVi-zkis_tPEvjbgz_82oTny6DHvdoq7nr4OD0Z0K6KhPUgHEu4u5hCvWGeBGKNq-TAQ

